### ISSUE TITLE
Querydatabase 

### ISSUE THREAD

**Issue by RemyYang** [lhanaf/MILD#1]
I run into a strange problem when call the function 'int query_database(cv::Mat descriptor, std::vector<float> &score);'. Values of the return score sometimes are much larger than 1.0, like over 200. I would like to ask what is the interval of value of score? Than you very much!

**Comment by lhanaf** [comment]
It's the similarity score defined in Eqn 3. The score could vary from 0 to infinity.
The simplest way to use this score is just consider the top 5 maximum values as loop closure candidates.
You can also try the Bayesian Inference, which will normalize the similarity score and output a loop closure probability, ranging from 0 to 1.

**Comment by RemyYang** [comment]
Than you very much for your reply! Your work is great! Is it possible that you could share a PDF of your IROS 2017 paper? Thanks again!

**Comment by lhanaf** [comment]
Sure, I just put this paper on arxiv: https://arxiv.org/abs/1709.05833
