### ISSUE TITLE
Ask for example image from 0000.png to 0010.png

### ISSUE THREAD

**Issue by zhanqan** [lhanaf/MILD#3]
Hello, I use my images to test your code, but it got 0 loop closure, actually it has 1 loop closure. So, can you provide your 11 test images for me? Thanks  a lot!

**Comment by jiayily** [comment]
Actually, there is a bug in the main.cpp of line 121. The getline() function will add the character '\r' to the end of the string in Linux. Change the code to:
    string input = line;
    input = input.substr(0, input.length()-1);
and watch out not to newline in the last line of imagelist.txt.

**Comment by lhanaf** [comment]
> Actually, there is a bug in the main.cpp of line 121. The getline() function will add the character '\r' to the end of the string in Linux. Change the code to:
> string input = line;
> input = input.substr(0, input.length()-1);
> and watch out not to newline in the last line of imagelist.txt.

Thanks for the mention. I will consider to fix this bug.

**Comment by lhanaf** [comment]
> Hello, I use my images to test your code, but it got 0 loop closure, actually it has 1 loop closure. So, can you provide your 11 test images for me? Thanks a lot!

Sorry for the late reply. You can test MILD on public dataset that are used in the papers. I'm not sure why it didn't work on your specific case.

**Comment by lhanaf** [comment]
> Hello, I use my images to test your code, but it got 0 loop closure, actually it has 1 loop closure. So, can you provide your 11 test images for me? Thanks a lot!

Not sure what do you mean by "11 test images".

**Comment by lhanaf** [comment]
> Hello, I use my images to test your code, but it got 0 loop closure, actually it has 1 loop closure. So, can you provide your 11 test images for me? Thanks a lot!

The 11 test images are just an example for the input of imagelist.txt. That is not a dataset image list and is not used for loop closure detection actually. A very easy to used dataset can be downloaded from:
http://www.robots.ox.ac.uk/~mobile/IJRR_2008_Dataset with groundtruth files: https://introlab.3it.usherbrooke.ca/mediawiki-introlab/images/5/5a/NewCollege.png (generated by introlab)
 

Best Regards
Lei Han

**Comment by jiayily** [comment]
Sorry, You code has no bug. It seems my txt file is wrong. And when I generate it using a python script, it's OK now. Sorry for my carelessness.

**Comment by lhanaf** [comment]
That's all right. Thanks for your interest in MILD.
