### ISSUE TITLE
imagelist.txt修改内容后输出的结果文件为空？

### ISSUE THREAD

**Issue by ghost** [lhanaf/MILD#4]

**Comment by dianqiliuze** [comment]
我找到问题所在了，很抱歉耽误您的时间

**Comment by dianqiliuze** [comment]
”Actually, there is a bug in the main.cpp of line 121. The getline() function will add the character '\r' to the end of the string in Linux. Change the code to:
string input = line;
input = input.substr(0, input.length()-1);
and watch out not to newline in the last line of imagelist.txt.
“

上述的公式中，第二行是不是需要修改为input = input.substr(0, input.length())？;
